name: ManSave
version: ${project.version}
main: cz.itoncek.mansave.ManSave
api-version: 1.16
authors: [ IToncek ]
description: MansavePlugin
load: STARTUP

commands:
  mansave:
    description: Various Mansave commands